package wx

const (
	OutTemp              = "outTemp"
	OutHumidity          = "outHumidity"
	InTemp               = "inTemp"
	InHumidity           = "inHumidity"
	Dewpoint             = "dewpoint"
	HeatIndex            = "heatindex"
	WindChill            = "windchill"
	Frostpoint           = "frostpoint"
	Barometer            = "barometer"
	Pressure             = "pressure"
	Altimeter            = "altimeter"
	WindSpeed            = "windSpeed"
	WindDir              = "windDir"
	WindGust             = "windGust"
	WindGustDir          = "windGustDir"
	Wind                 = "wind"
	Rain                 = "rain"
	RainRate             = "rainRate"
	UV                   = "UV"
	Radiation            = "radiation"
	Luminosity           = "luminosity"
	Cloudbase            = "cloudbase"
	LightningStrikeCount = "lightning_strike_count"
	LightningDistance    = "lightning_distance"
	LightningEnergy      = "lightning_energy"
	PM1                  = "pm1_0"
	PM25                 = "pm2_5"
	CO2                  = "co2"
	TVOC                 = "tvoc"
	OutRSSI              = "outRSSI"
	OutSNR               = "outSNR"
	OutNoise             = "outNoise"
	OutTempBattery       = "outTempBatteryStatus"
)
