// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type hTTPShadow struct {
	Bind *string `json:"bind" toml:"bind" yaml:"bind"`
	Port *int    `json:"port" toml:"port" yaml:"port"`
}

type mQTTShadow struct {
	Broker    *string `json:"broker"     toml:"broker"     yaml:"broker"`
	Username  *string `json:"username"   toml:"username"   yaml:"username"`
	Password  *string `json:"password"   toml:"password"   yaml:"password"`
	ClientID  *string `json:"client-id"  toml:"client-id"  yaml:"client-id"`
	Topic     *string `json:"topic"      toml:"topic"      yaml:"topic"`
	RainTopic *string `json:"rain-topic" toml:"rain-topic" yaml:"rain-topic"`
}

type stationShadow struct {
	Location      *string        `json:"location"         toml:"location"         yaml:"location"`
	Latitude      *float64       `json:"latitude"         toml:"latitude"         yaml:"latitude"`
	Longitude     *float64       `json:"longitude"        toml:"longitude"        yaml:"longitude"`
	AltitudeFeet  *float64       `json:"altitude-feet"    toml:"altitude-feet"    yaml:"altitude-feet"`
	Timezone      *impl.Location `json:"timezone"         toml:"timezone"         yaml:"timezone"`
	RainYearStart *int           `json:"rain-year-start"  toml:"rain-year-start"  yaml:"rain-year-start"`
	WeekStart     *int           `json:"week-start"       toml:"week-start"       yaml:"week-start"`
	ArchiveSecs   *int           `json:"archive-interval" toml:"archive-interval" yaml:"archive-interval"`
	RadarImage    *string        `json:"radar-image"      toml:"radar-image"      yaml:"radar-image"`
	RadarURL      *string        `json:"radar-url"        toml:"radar-url"        yaml:"radar-url"`
	SatelliteImg  *string        `json:"satellite-image"  toml:"satellite-image"  yaml:"satellite-image"`
	SatelliteURL  *string        `json:"satellite-url"    toml:"satellite-url"    yaml:"satellite-url"`
}

type databaseShadow struct {
	Path *string `json:"path" toml:"path" yaml:"path"`
}

type nWSShadow struct {
	Enabled   *bool          `json:"enabled"    toml:"enabled"    yaml:"enabled"`
	UserAgent *string        `json:"user-agent" toml:"user-agent" yaml:"user-agent"`
	Interval  *impl.Duration `json:"interval"   toml:"interval"   yaml:"interval"`
}

type configShadow struct {
	LogLevel *string         `json:"log-level" toml:"log-level" yaml:"log-level"`
	HTTP     *hTTPShadow     `json:"http"      toml:"http"      yaml:"http"`
	MQTT     *mQTTShadow     `json:"mqtt"      toml:"mqtt"      yaml:"mqtt"`
	Station  *stationShadow  `json:"station"   toml:"station"   yaml:"station"`
	Database *databaseShadow `json:"database"  toml:"database"  yaml:"database"`
	NWS      *nWSShadow      `json:"nws"       toml:"nws"       yaml:"nws"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
		Required:      []string{"station.location", "station.latitude", "station.longitude", "station.altitude-feet"},
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.HTTP.Bind = "[::]"
	set("http.bind", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = 8080
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.MQTT.Broker = "mqtt://localhost:1883"
	set("mqtt.broker", configulator.LayerDefault, "default tag")
	cfg.MQTT.ClientID = "wx"
	set("mqtt.client-id", configulator.LayerDefault, "default tag")
	cfg.MQTT.Topic = "weather/station"
	set("mqtt.topic", configulator.LayerDefault, "default tag")
	{
		var slot impl.Location
		_ = slot.UnmarshalText([]byte("UTC"))
		v, _ := slot.Value()
		cfg.Station.Timezone = v
		set("station.timezone", configulator.LayerDefault, "default tag")
	}
	cfg.Station.RainYearStart = 1
	set("station.rain-year-start", configulator.LayerDefault, "default tag")
	cfg.Station.WeekStart = 6
	set("station.week-start", configulator.LayerDefault, "default tag")
	cfg.Station.ArchiveSecs = 60
	set("station.archive-interval", configulator.LayerDefault, "default tag")
	cfg.Database.Path = "wx.db"
	set("database.path", configulator.LayerDefault, "default tag")
	cfg.NWS.Enabled = false
	set("nws.enabled", configulator.LayerDefault, "default tag")
	cfg.NWS.Interval = time.Duration(int64(1800000000000))
	set("nws.interval", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.HTTP != nil {
		if s.HTTP.Bind != nil {
			cfg.HTTP.Bind = *s.HTTP.Bind
			set("http.bind", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
	}
	if s.MQTT != nil {
		if s.MQTT.Broker != nil {
			cfg.MQTT.Broker = *s.MQTT.Broker
			set("mqtt.broker", configulator.LayerFile, file)
		}
		if s.MQTT.Username != nil {
			cfg.MQTT.Username = *s.MQTT.Username
			set("mqtt.username", configulator.LayerFile, file)
		}
		if s.MQTT.Password != nil {
			cfg.MQTT.Password = *s.MQTT.Password
			set("mqtt.password", configulator.LayerFile, file)
		}
		if s.MQTT.ClientID != nil {
			cfg.MQTT.ClientID = *s.MQTT.ClientID
			set("mqtt.client-id", configulator.LayerFile, file)
		}
		if s.MQTT.Topic != nil {
			cfg.MQTT.Topic = *s.MQTT.Topic
			set("mqtt.topic", configulator.LayerFile, file)
		}
		if s.MQTT.RainTopic != nil {
			cfg.MQTT.RainTopic = *s.MQTT.RainTopic
			set("mqtt.rain-topic", configulator.LayerFile, file)
		}
	}
	if s.Station != nil {
		if s.Station.Location != nil {
			cfg.Station.Location = *s.Station.Location
			set("station.location", configulator.LayerFile, file)
		}
		if s.Station.Latitude != nil {
			cfg.Station.Latitude = *s.Station.Latitude
			set("station.latitude", configulator.LayerFile, file)
		}
		if s.Station.Longitude != nil {
			cfg.Station.Longitude = *s.Station.Longitude
			set("station.longitude", configulator.LayerFile, file)
		}
		if s.Station.AltitudeFeet != nil {
			cfg.Station.AltitudeFeet = *s.Station.AltitudeFeet
			set("station.altitude-feet", configulator.LayerFile, file)
		}
		if s.Station.Timezone != nil {
			v, ok := s.Station.Timezone.Value()
			if !ok {
				return &configulator.OpaqueSpellingError{
					Hint: "\"America/New_York\"",
					Path: "station.timezone",
				}
			}
			cfg.Station.Timezone = v
			set("station.timezone", configulator.LayerFile, file)
		}
		if s.Station.RainYearStart != nil {
			cfg.Station.RainYearStart = *s.Station.RainYearStart
			set("station.rain-year-start", configulator.LayerFile, file)
		}
		if s.Station.WeekStart != nil {
			cfg.Station.WeekStart = *s.Station.WeekStart
			set("station.week-start", configulator.LayerFile, file)
		}
		if s.Station.ArchiveSecs != nil {
			cfg.Station.ArchiveSecs = *s.Station.ArchiveSecs
			set("station.archive-interval", configulator.LayerFile, file)
		}
		if s.Station.RadarImage != nil {
			cfg.Station.RadarImage = *s.Station.RadarImage
			set("station.radar-image", configulator.LayerFile, file)
		}
		if s.Station.RadarURL != nil {
			cfg.Station.RadarURL = *s.Station.RadarURL
			set("station.radar-url", configulator.LayerFile, file)
		}
		if s.Station.SatelliteImg != nil {
			cfg.Station.SatelliteImg = *s.Station.SatelliteImg
			set("station.satellite-image", configulator.LayerFile, file)
		}
		if s.Station.SatelliteURL != nil {
			cfg.Station.SatelliteURL = *s.Station.SatelliteURL
			set("station.satellite-url", configulator.LayerFile, file)
		}
	}
	if s.Database != nil {
		if s.Database.Path != nil {
			cfg.Database.Path = *s.Database.Path
			set("database.path", configulator.LayerFile, file)
		}
	}
	if s.NWS != nil {
		if s.NWS.Enabled != nil {
			cfg.NWS.Enabled = *s.NWS.Enabled
			set("nws.enabled", configulator.LayerFile, file)
		}
		if s.NWS.UserAgent != nil {
			cfg.NWS.UserAgent = *s.NWS.UserAgent
			set("nws.user-agent", configulator.LayerFile, file)
		}
		if s.NWS.Interval != nil {
			v, ok := s.NWS.Interval.Value()
			if !ok {
				return &configulator.OpaqueSpellingError{
					Hint: "\"30s\"",
					Path: "nws.interval",
				}
			}
			cfg.NWS.Interval = v
			set("nws.interval", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "bind"); ok {
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = int(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "broker"); ok {
		cfg.MQTT.Broker = v
		set("mqtt.broker", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "username"); ok {
		cfg.MQTT.Username = v
		set("mqtt.username", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "password"); ok {
		cfg.MQTT.Password = v
		set("mqtt.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "client-id"); ok {
		cfg.MQTT.ClientID = v
		set("mqtt.client-id", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "topic"); ok {
		cfg.MQTT.Topic = v
		set("mqtt.topic", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "rain-topic"); ok {
		cfg.MQTT.RainTopic = v
		set("mqtt.rain-topic", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "location"); ok {
		cfg.Station.Location = v
		set("station.location", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "latitude"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.latitude",
				Source: n,
				Value:  v,
			}
		}
		cfg.Station.Latitude = p
		set("station.latitude", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "longitude"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.longitude",
				Source: n,
				Value:  v,
			}
		}
		cfg.Station.Longitude = p
		set("station.longitude", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "altitude-feet"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.altitude-feet",
				Source: n,
				Value:  v,
			}
		}
		cfg.Station.AltitudeFeet = p
		set("station.altitude-feet", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "timezone"); ok {
		var slot impl.Location
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.timezone",
				Source: n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Station.Timezone = sv
		set("station.timezone", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "rain-year-start"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.rain-year-start",
				Source: n,
				Value:  v,
			}
		}
		cfg.Station.RainYearStart = int(p)
		set("station.rain-year-start", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "week-start"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.week-start",
				Source: n,
				Value:  v,
			}
		}
		cfg.Station.WeekStart = int(p)
		set("station.week-start", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "archive-interval"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.archive-interval",
				Source: n,
				Value:  v,
			}
		}
		cfg.Station.ArchiveSecs = int(p)
		set("station.archive-interval", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "radar-image"); ok {
		cfg.Station.RadarImage = v
		set("station.radar-image", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "radar-url"); ok {
		cfg.Station.RadarURL = v
		set("station.radar-url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "satellite-image"); ok {
		cfg.Station.SatelliteImg = v
		set("station.satellite-image", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "station", "satellite-url"); ok {
		cfg.Station.SatelliteURL = v
		set("station.satellite-url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "database", "path"); ok {
		cfg.Database.Path = v
		set("database.path", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "nws", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nws.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.NWS.Enabled = p
		set("nws.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "nws", "user-agent"); ok {
		cfg.NWS.UserAgent = v
		set("nws.user-agent", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "nws", "interval"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nws.interval",
				Source: n,
				Value:  v,
			}
		}
		cfg.NWS.Interval = d
		set("nws.interval", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"log-level",
		"http" + o.Separator + "bind",
		"http" + o.Separator + "port",
		"mqtt" + o.Separator + "broker",
		"mqtt" + o.Separator + "username",
		"mqtt" + o.Separator + "password",
		"mqtt" + o.Separator + "client-id",
		"mqtt" + o.Separator + "topic",
		"mqtt" + o.Separator + "rain-topic",
		"station" + o.Separator + "location",
		"station" + o.Separator + "latitude",
		"station" + o.Separator + "longitude",
		"station" + o.Separator + "altitude-feet",
		"station" + o.Separator + "timezone",
		"station" + o.Separator + "rain-year-start",
		"station" + o.Separator + "week-start",
		"station" + o.Separator + "archive-interval",
		"station" + o.Separator + "radar-image",
		"station" + o.Separator + "radar-url",
		"station" + o.Separator + "satellite-image",
		"station" + o.Separator + "satellite-url",
		"database" + o.Separator + "path",
		"nws" + o.Separator + "enabled",
		"nws" + o.Separator + "user-agent",
		"nws" + o.Separator + "interval",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.String(names[1], "[::]", "Address to listen on. The default, [::], listens on all interfaces")
	fs.Var(impl.NewInt(8080), names[2], "Port to listen on")
	fs.String(names[3], "mqtt://localhost:1883", "MQTT broker URL")
	fs.String(names[4], "", "MQTT username")
	fs.String(names[5], "", "MQTT password")
	fs.String(names[6], "wx", "MQTT client ID")
	fs.String(names[7], "weather/station", "Topic carrying mqtt-wx station packets in weewx METRICWX units")
	fs.String(names[8], "", "Optional rtl_433 topic whose rain_mm counter is used for rain instead of the station packet")
	fs.String(names[9], "", "Station name shown in the title bar")
	fs.Float64(names[10], 0.0, "Station latitude in degrees, north positive")
	fs.Float64(names[11], 0.0, "Station longitude in degrees, east positive")
	fs.Float64(names[12], 0.0, "Altitude of the pressure sensor in feet, used to reduce station pressure to sea level")
	fs.String(names[13], "UTC", "Timezone used for day boundaries and display")
	fs.Var(impl.NewInt(1), names[14], "Month the rain year starts in")
	fs.Var(impl.NewInt(6), names[15], "Day the week starts on, 0 is Monday and 6 is Sunday")
	fs.Var(impl.NewInt(60), names[16], "Archive record interval in seconds")
	fs.String(names[17], "", "Radar image URL")
	fs.String(names[18], "", "Radar link URL")
	fs.String(names[19], "", "Satellite image URL")
	fs.String(names[20], "", "Satellite link URL")
	fs.String(names[21], "wx.db", "Path to the SQLite archive database")
	fs.Bool(names[22], false, "Fetch NWS forecasts and alerts")
	fs.String(names[23], "", "User-Agent sent to api.weather.gov, which asks for a contact such as (site, email)")
	fs.Duration(names[24], time.Duration(int64(1800000000000)), "How often to refresh the forecast")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "bind"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.bind",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Bind = v
		set("http.bind", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "broker"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.broker",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Broker = v
		set("mqtt.broker", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "username"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.username",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Username = v
		set("mqtt.username", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.password",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Password = v
		set("mqtt.password", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "client-id"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.client-id",
				Source: "--" + n,
			}
		}
		cfg.MQTT.ClientID = v
		set("mqtt.client-id", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "topic"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.topic",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Topic = v
		set("mqtt.topic", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "rain-topic"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.rain-topic",
				Source: "--" + n,
			}
		}
		cfg.MQTT.RainTopic = v
		set("mqtt.rain-topic", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "location"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.location",
				Source: "--" + n,
			}
		}
		cfg.Station.Location = v
		set("station.location", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "latitude"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.latitude",
				Source: "--" + n,
			}
		}
		cfg.Station.Latitude = v
		set("station.latitude", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "longitude"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.longitude",
				Source: "--" + n,
			}
		}
		cfg.Station.Longitude = v
		set("station.longitude", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "altitude-feet"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.altitude-feet",
				Source: "--" + n,
			}
		}
		cfg.Station.AltitudeFeet = v
		set("station.altitude-feet", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "timezone"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.timezone",
				Source: "--" + n,
			}
		}
		var slot impl.Location
		if err := slot.UnmarshalText([]byte(v)); err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.timezone",
				Source: "--" + n,
				Value:  v,
			}
		}
		sv, _ := slot.Value()
		cfg.Station.Timezone = sv
		set("station.timezone", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "rain-year-start"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.rain-year-start",
				Source: "--" + n,
			}
		}
		cfg.Station.RainYearStart = v
		set("station.rain-year-start", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "week-start"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.week-start",
				Source: "--" + n,
			}
		}
		cfg.Station.WeekStart = v
		set("station.week-start", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "archive-interval"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.archive-interval",
				Source: "--" + n,
			}
		}
		cfg.Station.ArchiveSecs = v
		set("station.archive-interval", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "radar-image"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.radar-image",
				Source: "--" + n,
			}
		}
		cfg.Station.RadarImage = v
		set("station.radar-image", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "radar-url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.radar-url",
				Source: "--" + n,
			}
		}
		cfg.Station.RadarURL = v
		set("station.radar-url", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "satellite-image"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.satellite-image",
				Source: "--" + n,
			}
		}
		cfg.Station.SatelliteImg = v
		set("station.satellite-image", configulator.LayerCLI, "--"+n)
	}
	if n := "station" + o.Separator + "satellite-url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "station.satellite-url",
				Source: "--" + n,
			}
		}
		cfg.Station.SatelliteURL = v
		set("station.satellite-url", configulator.LayerCLI, "--"+n)
	}
	if n := "database" + o.Separator + "path"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "database.path",
				Source: "--" + n,
			}
		}
		cfg.Database.Path = v
		set("database.path", configulator.LayerCLI, "--"+n)
	}
	if n := "nws" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nws.enabled",
				Source: "--" + n,
			}
		}
		cfg.NWS.Enabled = v
		set("nws.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "nws" + o.Separator + "user-agent"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nws.user-agent",
				Source: "--" + n,
			}
		}
		cfg.NWS.UserAgent = v
		set("nws.user-agent", configulator.LayerCLI, "--"+n)
	}
	if n := "nws" + o.Separator + "interval"; fs.Changed(n) {
		v, err := fs.GetDuration(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "nws.interval",
				Source: "--" + n,
			}
		}
		cfg.NWS.Interval = v
		set("nws.interval", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "mqtt":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("mqtt", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub mQTTShadow
				if err := sub.decodeJSON(dec, "mqtt"); err != nil {
					return err
				}
				s.MQTT = &sub
			}
		case "station":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("station", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub stationShadow
				if err := sub.decodeJSON(dec, "station"); err != nil {
					return err
				}
				s.Station = &sub
			}
		case "database":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("database", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub databaseShadow
				if err := sub.decodeJSON(dec, "database"); err != nil {
					return err
				}
				s.Database = &sub
			}
		case "nws":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("nws", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub nWSShadow
				if err := sub.decodeJSON(dec, "nws"); err != nil {
					return err
				}
				s.NWS = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "bind":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bind = &str
			default:
				return configJSONError(path+".bind", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *mQTTShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "broker":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Broker = &str
			default:
				return configJSONError(path+".broker", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "username":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Username = &str
			default:
				return configJSONError(path+".username", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "password":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.Password = &str
				default:
					return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".password",
					Value: "(redacted)",
				}
			}
		case "client-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ClientID = &str
			default:
				return configJSONError(path+".client-id", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "topic":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Topic = &str
			default:
				return configJSONError(path+".topic", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "rain-topic":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.RainTopic = &str
			default:
				return configJSONError(path+".rain-topic", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *stationShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "location":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Location = &str
			default:
				return configJSONError(path+".location", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "latitude":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError(path+".latitude", v, err)
				}
				s.Latitude = &num
			default:
				return configJSONError(path+".latitude", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "longitude":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError(path+".longitude", v, err)
				}
				s.Longitude = &num
			default:
				return configJSONError(path+".longitude", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "altitude-feet":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError(path+".altitude-feet", v, err)
				}
				s.AltitudeFeet = &num
			default:
				return configJSONError(path+".altitude-feet", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "timezone":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				var slot impl.Location
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return configJSONError(path+".timezone", v, err)
				}
				s.Timezone = &slot
			default:
				return configJSONError(path+".timezone", v, fmt.Errorf("expected a text scalar (e.g. \"America/New_York\"), got %v", v.Kind()))
			}
		case "rain-year-start":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".rain-year-start", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".rain-year-start", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.RainYearStart = &num
			default:
				return configJSONError(path+".rain-year-start", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "week-start":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".week-start", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".week-start", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.WeekStart = &num
			default:
				return configJSONError(path+".week-start", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "archive-interval":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".archive-interval", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".archive-interval", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.ArchiveSecs = &num
			default:
				return configJSONError(path+".archive-interval", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "radar-image":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.RadarImage = &str
			default:
				return configJSONError(path+".radar-image", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "radar-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.RadarURL = &str
			default:
				return configJSONError(path+".radar-url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "satellite-image":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.SatelliteImg = &str
			default:
				return configJSONError(path+".satellite-image", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "satellite-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.SatelliteURL = &str
			default:
				return configJSONError(path+".satellite-url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *databaseShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "path":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Path = &str
			default:
				return configJSONError(path+".path", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *nWSShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "user-agent":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.UserAgent = &str
			default:
				return configJSONError(path+".user-agent", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "interval":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				var slot impl.Duration
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return configJSONError(path+".interval", v, err)
				}
				s.Interval = &slot
			default:
				return configJSONError(path+".interval", v, fmt.Errorf("expected a text scalar (e.g. \"30s\"), got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "http.bind = %v\n", c.HTTP.Bind)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "mqtt.broker = %v\n", c.MQTT.Broker)
	fmt.Fprintf(&b, "mqtt.username = %v\n", c.MQTT.Username)
	b.WriteString("mqtt.password = (redacted)\n")
	fmt.Fprintf(&b, "mqtt.client-id = %v\n", c.MQTT.ClientID)
	fmt.Fprintf(&b, "mqtt.topic = %v\n", c.MQTT.Topic)
	fmt.Fprintf(&b, "mqtt.rain-topic = %v\n", c.MQTT.RainTopic)
	fmt.Fprintf(&b, "station.location = %v\n", c.Station.Location)
	fmt.Fprintf(&b, "station.latitude = %v\n", c.Station.Latitude)
	fmt.Fprintf(&b, "station.longitude = %v\n", c.Station.Longitude)
	fmt.Fprintf(&b, "station.altitude-feet = %v\n", c.Station.AltitudeFeet)
	fmt.Fprintf(&b, "station.timezone = %v\n", c.Station.Timezone)
	fmt.Fprintf(&b, "station.rain-year-start = %v\n", c.Station.RainYearStart)
	fmt.Fprintf(&b, "station.week-start = %v\n", c.Station.WeekStart)
	fmt.Fprintf(&b, "station.archive-interval = %v\n", c.Station.ArchiveSecs)
	fmt.Fprintf(&b, "station.radar-image = %v\n", c.Station.RadarImage)
	fmt.Fprintf(&b, "station.radar-url = %v\n", c.Station.RadarURL)
	fmt.Fprintf(&b, "station.satellite-image = %v\n", c.Station.SatelliteImg)
	fmt.Fprintf(&b, "station.satellite-url = %v\n", c.Station.SatelliteURL)
	fmt.Fprintf(&b, "database.path = %v\n", c.Database.Path)
	fmt.Fprintf(&b, "nws.enabled = %v\n", c.NWS.Enabled)
	fmt.Fprintf(&b, "nws.user-agent = %v\n", c.NWS.UserAgent)
	fmt.Fprintf(&b, "nws.interval = %v\n", c.NWS.Interval)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
